---
title: "Lab8"
author: "yingtong lyu"
date: "November 5, 2018"
output: pdf_document
---


#1. Re-formate the code according to the style guide

```{r cars}
prime <- function(n){
  if(n %% 1 != 0 | n < 0){
    return (FALSE)
  } else if (n == 1) {
      return (FALSE)
  } else if (n == 2) {
      return (TRUE)
  } else {
      for(i in 2:(sqrt(n))){
        if(n %% i==0){
           return (FALSE)
        }
      }
    return (TRUE)
    }
  }
```

#2. Re-format and debug the function
```{r}
find_runs <- function(x,k) {
  n=length(x)
  runs = NULL
  for(i in 1:(n-k+1)) {
    if(all(x[i:i+k-1]==1)) 
       runs=c(runs,i)
  }
  return (runs)
}
find_runs(c(1,0,0,1,1,0,1,1,1),2)
```
#3. Debug the following function
```{r}
sort_vec = function(x) {
  
  if (length(x) < 2) 
    return (x)
  
  for(last in length(x):2) {
    for(first in 1:(last - 1)) {
      if(x[first] > x[first + 1]) {
        temp <- x[first]
        x[first] <- x[first + 1]
        x[first + 1] <- temp
      }
    }
  }
  return(x)
}
x <- c(3,1,2)
sort_vec(x)

```

